### ISSUE TITLE
How does polaris get the album + artist name?

### ISSUE THREAD

**Issue by HolyStephano** [agersant/polaris#102]
I've recently installed polaris and i can't seem to find any documentation on how the album name and artist name are pulled from the filesystem.

**Comment by agersant** [comment]
Hello!

Album names and song titles are pulled from the metadata inside the files. Most commonly, that would be ID3 tags within mp3 files, although some other tag formats are supported.

Note that when browsing your collection, the structure you traverse maps directly to directories on your file system (which means all albums by the same artist are not necessarily in the same directory).

If you happen to know Rust, the code handling extraction of metadata is [here](https://github.com/agersant/polaris/blob/master/src/index/metadata.rs).
