### ISSUE TITLE
Music library does not update.

### ISSUE THREAD

**Issue by stukkat** [agersant/polaris#124]
Polaris version : 0.13.2
Platform : Windows 10

Polaris does not seem to update the music library after the initial scan.

For example if Polaris first scans a file at "C:\Music\MusicFile.mp3" and you move the file to to "C:\Music\Artist\MusicFile.mp3"
followed by doing a manual scan (or waiting for the automatic scan)
Polaris will display the newly moved file, but it will not delete the old entry and will continue to display and try to play "C:\Music\MusicFile.mp3".

edit: Edited for clarity.

**Comment by agersant** [comment]
Good find! Fixed in 7bc8e142c36e4cb00568e50f1116588a1c66f3ef.

I'm going to look into adding a unit test for this too.

**Comment by agersant** [comment]
Test added https://github.com/agersant/polaris/blob/7edcc38483539ce56ffa3bb6f7c209291e6c9885/src/app/index/test.rs#L29
