### ISSUE TITLE
Consider using native-windows-gui to manage system tray icon on Windows

### ISSUE THREAD

**Issue by agersant** [agersant/polaris#126]
Would remove a bunch of code, including the only `unsafe` blocks in the codebase.

https://github.com/gabdube/native-windows-gui

Example: https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/system_tray_d.rs

**Comment by lnicola** [comment]
There's also https://crates.io/crates/systray.

**Comment by lnicola** [comment]
Or maybe not: https://www.reddit.com/r/rust/comments/kmra1w/deprecating_systrayrs/

NWG seems quite heavy, though.

**Comment by agersant** [comment]
Implemented and released (alongside some other improvements in this area) 🚀.

No significant difference in executable size or build time.

**Comment by agersant** [comment]
The reddit thread you linked is what got me thinking about this in the first place!
