### ISSUE TITLE
Don't create log file when `-f` option is set and the `--log` option not is set

### ISSUE THREAD

**Issue by ogarcia** [agersant/polaris#128]
In latest version 0.13.3 the log file is created even when running with the `-f` option. I think that this is a good idea only if the user set the `--log` option, because when you run the app in forenground is because you have a daemon controler (like `systemd`) that collect the log and write the logfile is redundant in this case.

**Comment by agersant** [comment]
That's a fair point. Adjusted behavior in https://github.com/agersant/polaris/commit/7a73ae7cc0656956b13917e5458b117161401b4d

On Linux:
- Running without `-f` emits a log file
- Running with `-f` and no `--log` option does not emit a log file
- Running with `-f` and `--log` option emits a log file

On Windows:
- Running with UI feature (`polaris.exe` in releases) emits a log file
- Running without UI feature (`polaris-cli.exe` in releases) and no `--log` option does not emit a log file
- Running without UI feature (`polaris-cli.exe` in releases) and `--log` option emits a log file
