### ISSUE TITLE
404 when loading / on locally built installation

### ISSUE THREAD

**Issue by ahockersten** [agersant/polaris#130]
Hello. I've been trying to get a dev environment for Polaris up and running, according to the instructions in https://github.com/agersant/polaris/blob/6c27409ef2674c728fad625552c481e3a3bab717/docs/CONTRIBUTING.md

I am starting Polaris with `cargo run -- -f -w web -s docs/swagger -d test-output/my.db`. When I go to `localhost:5050` I simply get a 404, and the console logs:
```
10:42:17 [INFO] [/home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 127.0.0.1:41802 "GET / HTTP/1.1" 404 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" 0.000641
```

If I go to `http://localhost:5050/swagger/` I can see the swagger documentation, so some routes are working at least.

I have a strong suspicion this is related to me not having run Polaris before so my database and configs are all empty.

Additional info: Running `cargo test` reports no test errors. I tried building the latest release tag (`0.13.4`) and got the same error. This is on Ubuntu 20.10.

Full console output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/polaris -f -w web -s docs/swagger -d test-output/my.db`
10:42:11 [INFO] [src/main.rs:98] Cache files location is "."
10:42:11 [INFO] [src/main.rs:99] Config files location is None
10:42:11 [INFO] [src/main.rs:100] Database file location is "test-output/my.db"
10:42:11 [INFO] [src/main.rs:101] Log file location is None
10:42:11 [INFO] [src/main.rs:106] Swagger files location is "docs/swagger"
10:42:11 [INFO] [src/main.rs:107] Web client files location is "web"
10:42:11 [INFO] [src/main.rs:115] Starting up server
10:42:11 [INFO] [src/app/index/update/mod.rs:19] Beginning library index update
10:42:11 [INFO] [src/ui/headless.rs:6] Starting up UI (headless)
10:42:11 [INFO] [src/app/ddns/manager.rs:26] Skipping DDNS update because credentials are missing
10:42:11 [INFO] [/home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:263] Starting 8 workers
10:42:11 [INFO] [/home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:277] Starting "actix-web-service-0.0.0.0:5050" service on 0.0.0.0:5050
10:42:11 [INFO] [src/app/index/update/traverser.rs:53] Browsing collection using 4 threads
10:42:11 [INFO] [src/app/index/update/mod.rs:58] Library index update took 0.003 seconds
10:42:17 [INFO] [/home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 127.0.0.1:41802 "GET / HTTP/1.1" 404 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" 0.000641
```

**Comment by agersant** [comment]
Hello!

Empty configs and database should not be an issue. Did you extract files for the web client and place them within in the `web` directory you are trying to serve? 

Directory structure should look like:

```
polaris
  Cargo.toml
  README.md
  src
  web
```

(some files omitted for brevity)

**Comment by ahockersten** [comment]
I did not! If I check out the web repo and build it, it works, of course. And now that I reread `CONTRIBUTING.md` I can see that yes, it does state I should do that. :blush: 

Maybe the instructions could be clearer. It's not super obvious from Polaris' landing page that the project is split into a separate frontend and backend repository. Maybe I'll try to submit a patch with suggestion for documentation improvements to the effect of making this clearer?

Thank you for your help! <3

**Comment by agersant** [comment]
Glad you got it working. Improvements to the documentation are always welcome if you have the time!
