### ISSUE TITLE
Support for wav files

### ISSUE THREAD

**Issue by gahag** [agersant/polaris#132]
I would be very interested in adding support for wav files, as there are many in my music library. Is the project willing to have this feature? I'd be happy to contribute.

**Comment by agersant** [comment]
Hello! Support for wave files would be a welcome contribution, thank you for asking!

Note however that Polaris doesn't do any transcoding when you stream, so wave files will use a lot of bandwidth.

**Comment by gahag** [comment]
I took a brief look at the codebase in order to feel what the implementation might look like. I noticed, as you said, that Polaris doesn't do any kind of transcoding. Would it be enough to just add the relevant enum fields for wav, and related minor changes?

**Comment by agersant** [comment]
As you identified, changes to Polaris itself would be pretty limited:
- Add relevant enum value
- Detect format from file extension
- Update metadata parsing (https://github.com/agersant/polaris/blob/6c27409ef2674c728fad625552c481e3a3bab717/src/app/index/metadata.rs#L30)
- Add tests

The big catch is I don't think there exists a Rust library which can read ID3 tags from a `wav` file. I just did a quick search and most libraries seem to focus on finding and decoding the audio data. I would be hesitant to accept a contribution without metadata parsing, as these files would end up looking pretty sad in the existing clients.

**Comment by gahag** [comment]
That seems pretty easy. I'm willing to make those changes and submit a pull request. Regarding the metadata support, I would argue that it would be better to have sad looking files than to not have those files at all. But I believe we can work out the metadata extraction for wave files easily, as the ID3 format is almost the same for different audio formats. The id3 crate even [mentions](https://github.com/polyfloyd/rust-id3/blob/dfa7e689d96efa7051898376191f8e749967afc1/src/storage.rs#L5) wav support, so I think it will probably just work. I can start working on this as soon as you approve.

**Comment by agersant** [comment]
That would be ideal as `rust-id3` is already a Polaris dependency, let's give it a try!

**Comment by gahag** [comment]
I have filled a [pull request](https://github.com/polyfloyd/rust-id3/pull/64) for rust-id3 to add support for wave files. As soon as it gets merged, I'll start working on Polaris.
