### ISSUE TITLE
Album Art Pattern

### ISSUE THREAD

**Issue by hg2s** [agersant/polaris#136]
I'm a little confused about Album Art Pattern. 

Can I supply an image, say, cover.jpg to a folder for an album that does not have embedded artwork and have it used as cover art provided I specify the pattern as cover.(jpg|jpeg|png) in Settings > Collection?

**Comment by agersant** [comment]
Correct! The pattern you posted would detect files named any of the following:

- `cover.jpg`
- `cover.jpeg`
- `cover.png`

Note that you have to trigger a scan of the collection (or wait for the periodic scan) for artwork to be detected.

**Comment by hg2s** [comment]
OK, got it. 

Can I specify a default (generic) album image in case artwork is missing?

**Comment by agersant** [comment]
No that isn't supported at the moment.
