### ISSUE TITLE
Playlist repeat options not working

### ISSUE THREAD

**Issue by gahag** [agersant/polaris#142]
In the latest version of Polaris, I noticed that the 'Repeat all' and 'Repeat track' options do not work in the web client. Can you reproduce this error?

**Comment by hg2s** [comment]
"Repeat all" is working; "Repeat track" is not. 

Firefox 88.

**Comment by agersant** [comment]
Good catch! I can repro too.

**Comment by gahag** [comment]
I have tested with both Chromium and Firefox on Arch Linux, and both repeat options don't seem to work. Please let me know if I can help with anything.

**Comment by agersant** [comment]
Moved here: https://github.com/agersant/polaris-web/issues/91
