### ISSUE TITLE
Add API parameter for thumbnail size

### ISSUE THREAD

**Issue by Saecki** [agersant/polaris#143]
Currently the thumbnail resolution always defaults to 400x400. While that is fine for previewing the thumbnail when browsing through the collection, it gets quite obvious when looking at the artwork in full size on the polaris android app for example.
The problem with allowing arbitrary sizes would be the amount of thumbnails that could be generated for the same artwork. So how about allowing predefined size parameters such as:
- `Resolution::Low`: 400x400,
- `Resolution::High`: 1200x1200
- `Resolution::Full`: native resolution

**Comment by agersant** [comment]
I am very much on board with this. I even paved the road for it by adding the thumbnail options struct when I last touched the thumbnail code🏗️!

I would want to think about the exact names and sizes before committing something to the API, but this is the right direction for sure.

(also apologies for the slow moving PRs, I haven't forgotten about them!)

**Comment by Saecki** [comment]
Great! After some more thinking I believe the size should probably also be a maximum size and not forced, so low resolution images don't get upscaled and use more bandwidth then necessary.
