### ISSUE TITLE
TTS based radio jockey - hosted playlist

### ISSUE THREAD

**Issue by pmphfm** [agersant/polaris#147]
I have a working prototype of a feature that adds voice based announcements between two songs. Currently the announcements is about the previous song information(sourced from tags) and about next song you will listen to. In future I intend to add more information like birthdays, trivia, etc by scarping sites like wiki. 

I want to know your thoughts and your willingness to accept such a patch.

# Bit about my approach.
- Right now TTS service is assumed to be service hosted outside of Polaris and polris can be configured to find where that service is.
- If rj is enabled, on queuing songs extra rows appear in playlist labeled "announcement".
- on finding the item to be announcement, the client reaches out to different API end point. Arguments to that API are next and prev songs
- Polaris server, with the help of TTS server, does magic and send mp3 of the announcement
- you can disable the feature anytime

# use cases
While working and driving I don't want to look at the screen for the information.

Ideally I want to add voice based controls in future.

Attached is a screenshot of web client that shows how "announcement item" will look like in a playlist. 
![IMG_20210605_095913_518](https://user-images.githubusercontent.com/82890237/120899474-c1d35500-c5e4-11eb-9461-6e98e291cc5d.jpg)

Thanks for reading.

**Comment by agersant** [comment]
Hello!

Thank you for the well thought-out proposal, I am very grateful for your willingness to improve Polaris. I do think this is a reasonable use case, and I am happy you found a way to solve for it.

However, I do think this feature is a bit out of scope for Polaris. I try to keep the program very minimalist and this is a bit too niche of an addition. This makes me think there may be room for a plugin system one day, for features like this one or the historical `Last.FM` integration (which isn't relevant to every user).
