### ISSUE TITLE
ordering by track number does not seem to work

### ISSUE THREAD

**Issue by mzagrabe** [agersant/polaris#151]
Hello,

I can't seem to order albums or playlists by track number:

![image](https://user-images.githubusercontent.com/4367686/135910206-3cf788b7-b67e-45bd-94e0-5e152e2b7485.png)

What am I missing to sort by track number?

Also, "Default" isn't a descriptive ordering.

Thanks!

-m

**Comment by agersant** [comment]
Hello!

The panel on the left shows your library as it appears on disk, and the files are listed by filename. Other sorting methods will hopefully be one day implemented along semantic browsing (https://github.com/agersant/polaris/issues/92).

The panel on the right shows your playlist, which could be a mix of songs from different artists/albums. There is currently no way to re-order songs in a playlist other than shuffling them by clicking the double-arrow icon at the top. I do want to implement selecting and moving songs with the mouse within the playlist eventually.
