### ISSUE TITLE
add filenames to "permission denied" error messages

### ISSUE THREAD

**Issue by mzagrabe** [agersant/polaris#152]
I am attempting to run polaris as a system user, but installed it via sudo (root). I am currently getting a variety of:

Error: Permission denied (os error 13)

but the error does not report the filename that needs the permission adjusted.

Please consider adding the filename to the error message.

Thank you!

**Comment by lnicola** [comment]
As a quick workaround, you can try running something like `sudo strace -e trace=open,openat,stat -fp $(pidof polaris)`, then triggering a reindex.

**Comment by mzagrabe** [comment]
Thanks for the hint, Laurențiu.

**Comment by agersant** [comment]
The error message comes from upstream code so it's also not obvious to me what caused it (yikes). Were you able to confirm that the offending file was something Polaris ran into while indexing? This would lower the surface area a bit to fix this.

**Comment by agersant** [comment]
Every possible error should now be accounted for in Polaris `0.14.0` 🚀
