### ISSUE TITLE
tracknumbers with total tracknumbers are not parsed

### ISSUE THREAD

**Issue by mzagrabe** [agersant/polaris#153]
Greetings,

I have a number of ogg vorbis files that were encoded a long time ago. Apparently the tagging software thought it would be nice to tag the tracknumbers like so:

TRACKNUMBER=01/09

as opposed to

TRACKNUMBER=01

Polaris does not successfully parse the former style of tracknumbers.

**Comment by lnicola** [comment]
I've seen that format in MP3 files of... Linux podcasts, maybe those OGGs were converted?
