### ISSUE TITLE
id3 panics and updating its version causes cargo dependency conflicts

### ISSUE THREAD

**Issue by jxs** [agersant/polaris#16]
id3 with some mp3 files panics due an [unwrap()](https://github.com/jameshurst/rust-id3/blob/0.2.0/src/frame/mod.rs#L76) that has since been [removed](https://github.com/jameshurst/rust-id3/blob/0.2.2/src/frame/mod.rs#L76) 

```  
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   7: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:71
   9: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:20
  11: <core::iter::TakeWhile<I, P> as core::iter::iterator::Iterator>::size_hint
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/frame/mod.rs:76
  12: id3::stream::frame::v2::decode
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/stream/frame/v2.rs:22
  13: id3::stream::frame::decode
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/stream/frame/mod.rs:16
  14: id3::stream::tag::decode
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/stream/tag.rs:76
  15: id3::tag::Tag::read_from
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/tag.rs:1359
  16: id3::tag::Tag::read_from_path
             at /Users/jxs/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-0.2.0/src/tag.rs:1365
  17: polaris::metadata::read_id3
             at src/metadata.rs:36
  18: polaris::metadata::read
             at src/metadata.rs:28
  19: polaris::index::IndexBuilder::populate_directory
             at src/index.rs:223
  20: polaris::index::IndexBuilder::populate_directory
             at src/index.rs:289
  21: polaris::index::populate
             at src/index.rs:373
  22: polaris::index::update
             at src/index.rs:386
  23: polaris::index::update_loop
             at src/index.rs:415
  24: polaris::run::{{closure}}
             at src/main.rs:179
```

I tried to update id3 to version `0.2.2`but due to it using a newer `byteorder` version (1.1.0) cargo refuses to compile with:

``` 
 error: failed to select a version for `byteorder` (required by `id3`):
 all possible versions conflict with previously selected versions of `byteorder` 
 version 1.0.0 in use by byteorder v1.0.0  
 version 0.4.2 in use by byteorder v0.4.2
 possible versions to select: 1.1.0
```

`rust-ape` uses version `0.4.2` so I tried to update rust-ape to byteorder `1.0.0`and depend on that rust-ape version, but i get a similar error:

``` 
 error: failed to select a version for `byteorder` (required by `id3`):
 all possible versions conflict with previously selected versions of `byteorder` 
 version 1.0.0 in use by byteorder v1.0.0  
 version 1.0.0 in use by byteorder v1.0.0  
 possible versions to select: 1.1.0
```

Do you have any idea on how to solve this?

meanwhile `ring` also started to give conflicts due to also having multiple versions being used, I was able to solve that by updating the main ring dependency, i will make a PR with those updates

thanks

**Comment by agersant** [comment]
I've had similar issues before with other parts of the dependency tree. I had good results entangling the web using [cargo tree](https://github.com/sfackler/cargo-tree) with the invert flag.

The possible solutions usually are:
- Finding compatible versions that have everything we want (best case scenario).
- Forking one of the dependency to update its dependencies and point Polaris' cargo.toml to our  version of it (using `git=...`).
- Using one of the newer [cargo features to override dependencies](http://doc.crates.io/manifest.html#the-patch-section). I have not tried this yet.

I can try looking at this specific problem this weekend. Out of curiosity, what kind of id3 tag triggers this bug?

**Comment by jxs** [comment]
nice didn't know cago patch, i'll read about it, but the other two were the ones I had in mind. 
The thing is, currently polaris is compiling with two `byteorder`versions 0.4.2 and 1.0.0 so why doesn't it compile with 1.0.0 and 1.1.0?  I thought cargo would just bundle the same dependency version for all the imported crates dependencies, but it doesn't seem to be the case

**Comment by jxs** [comment]
forgot to mention, the id3 is a id3 2.2 generated with logic pro 9.1

**Comment by jxs** [comment]
ok, found and address the problem with help from the #cargo folks at mozilla's irc: https://github.com/jameshurst/rust-metaflac/pull/5
let's wait for the PR to be merged and then use the updated versions, what do you think?

**Comment by agersant** [comment]
Perfect! Thanks a lot for chasing the issue. Also thanks @jameshurst for the quick turnaround time.
