### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by ziabskiK** [agersant/polaris#162]
Hi,

What are the possibilities for Responsive app design?

I was looking for home audio streaming solution and found this awesome project.

There is Android client available but what abaout iOS app? I'm using Apple Safari 14.8 web client and it's hard to use on mobile. Changing audio position doesn't work.

**Comment by Saecki** [comment]
The android client is currently being rewritten in flutter, which would allow also distributing an ios app.

**Comment by agersant** [comment]
Hello and thanks for trying out Polaris!

@Saecki is correct: the strategy is to have the web client support desktop/laptop use cases (not responsive), and mobile apps for touch devices. The Android client is being rewritten in Flutter, which will make it possible to ship to iOS. However, that would still hinge on contributors as I don't have Apple hardware to develop with 😔.

Until then, there is no good way to use Polaris on iOS devices.

**Comment by ziabskiK** [comment]
Thank you for your quick reply.
