### ISSUE TITLE
Changing playback rate

### ISSUE THREAD

**Issue by ziabskiK** [agersant/polaris#163]
Is it possible to change playback rate? 

For example changing audio to 1.25x playback rate.

**Comment by agersant** [comment]
This is currently not possible. If you are using the web client, you could use your browser's developer tools to adjust the `playbackRate` property on the `<audio>` element in the page.

**Comment by ziabskiK** [comment]
Thank you for information.
What about extending toolbar with some select Button with playback rate options?
