### ISSUE TITLE
excessive CPU usage

### ISSUE THREAD

**Issue by mzagrabe** [agersant/polaris#164]
Hello,

Polaris is using a bit of CPU when nothing is happening with the system, nor have any files changed:

![image](https://user-images.githubusercontent.com/4367686/147508338-1654a16d-c96e-4dba-82b4-011352edec03.png)

Is there a good way to find out what Polaris is doing to help track down why the CPU is churning so much? This has been happening since initial install months ago; I'm just now getting around to submitting an issue.

Thanks for any help!

**Comment by mzagrabe** [comment]
I should say the column with the 16.4, 22.9, 24.2, 13.1 is the % CPU usage.

**Comment by lnicola** [comment]
It's probably rescanning your media library to find new files. There's no support yet for file watching (#5).

**Comment by agersant** [comment]
@lnicola is most likely correct. Please report back if you see excessive CPU usage outside of collection scan windows (logs indicate start/end times).
