### ISSUE TITLE
can't use a question mark when naming playlists

### ISSUE THREAD

**Issue by maczones10** [agersant/polaris#167]
When I include a question mark ["?"] in the name of any of my playlists, the playlist creation subwindow acts as normal, saying "Saved!" and my playlist name appears with all the others. However, the trouble appears when I select that playlist: the entire box that is typically filled with the name of the playlist, the buttons to either "Play" or "Delete" the playlist, and the songs of the playlist are entirely missing, leaving the box empty. A strange side effect of this means that I now have no means of deleting my useless playlist.

A related note I found strange: If I create a playlist titled "How Can I Be Sure?" the process fails as described above. But if I were to then create another playlist without that ending question mark in the name (titled "How Can I Be Sure") it saves as expected, but then when I select the broken original playlist (the one with the question mark: ["How Can I Be Sure? I Don't Know"]) it links to the second playlist; the one that works. From what I can tell, when selecting, it ignores everything following the question mark and then brings up the playlist that works (that being the second playlist in this example).

Hope this helps.

**Comment by agersant** [comment]
Thank you for the good report!
This was a bug in the web client, which is now fixed (https://github.com/agersant/polaris-web/commit/fcebab6df67dbb99beaa5a78be217aff4f106206). This will be deployed in the next release (no ETA).
