### ISSUE TITLE
certain tracks don't highlight in playlist

### ISSUE THREAD

**Issue by mzagrabe** [agersant/polaris#168]
Hi,

I'm able to cue up songs and sometimes when the song is played (and finishes) the next song is the first song in the playlist instead of the actual next song in the playlist.

I've just noticed this today and the song isn't highlighted in the playlist either:

![image](https://user-images.githubusercontent.com/4367686/151052664-2b8fe127-c3c6-4a82-b347-509a4c9d0701.png)

I am playing the Santana Evil Ways Pop Music - The Golden Era 1951-1975 (disc 2) (1999) #13, as you can see in the lower part of the screen shot. However the song isn't highlighted (blue) in the playlist as other playing songs normally are (with a little "play" icon.)

Once the song finishes, the next song that plays is the first song in the playlist, not the "Black Magic Woman".

Thanks for your help!

**Comment by agersant** [comment]
Hello and thank you for the report. I am unable to reproduce the issue on my setup, could you provide step-by-step instructions to reproduce and the necessary media files?

**Comment by mzagrabe** [comment]
Here is how I reproduce it:

Cue up an album from "Music Collection". Call it album A.
Add a search for song from "Search". Call it song S.
Cue up another album from "Music Collection". Call it album B.

Play song S. That song is not highlighted. Once  song S finishes the next song that plays is album A, not album B.

I do have my patch applied for sorting applied:

https://github.com/agersant/polaris/pull/156/files

...and I don't think that patch would affect this issue.

Let me know if the above reproduction steps work for you.

Thank you!

-m

**Comment by agersant** [comment]
The repro steps work, thank you! I'll take a look ASAP.

**Comment by agersant** [comment]
Fixed here https://github.com/agersant/polaris-web/commit/d2705fdb91d874f863ec1abe8f9e4616a6a1303d

**Comment by mzagrabe** [comment]
Hi @agersant ,

What would be the best way to patch a running polaris instance to get this JS fix? It looks like the JS is minified, so directly patching doesn't seem sensible. The latest release of polaris is from 2021 and I don't believe it would have this fix.

Thanks for any help!

-m

**Comment by Saecki** [comment]
@mzagrabe The frontend can be found [here](https://github.com/agersant/polaris-web/releases)

**Comment by mzagrabe** [comment]
Thank you @Saecki !

**Comment by agersant** [comment]
Beat me to it!
