### ISSUE TITLE
Trouble with folder images

### ISSUE THREAD

**Issue by Brancliff** [agersant/polaris#169]
I have two folders - Folder A and Folder B. Folder B has a folder image, but folder A does not.

I'm not sure how Folder B got the folder image, since there are no imagefiles in the directory. Did it grab the embedded image from one of the audio tracks? Maybe, but folder A's tracks all have the same embedded image and it didn't grab any of those.

In the settings, it states that the format for grabbing folder art is "Folder.(jpeg|jpg|png)". So I made folder.jpeg, folder.jpg, and folder.png, put them all in Folder A, hit the rescan button, and still don't have a folder image.

**Comment by agersant** [comment]
Hello and thank you for the report. I am unable to reproduce the issue on my setup, could you provide a zip file with the content of Folder A and Folder B so I can investigate?
