### ISSUE TITLE
Compilation unsucessful

### ISSUE THREAD

**Issue by pirona** [agersant/polaris#170]
Hello,

I'm trying to compile polaris but it fails everytime on the same supposedly unstable library : 

```
cargo build --release
   Compiling mp4ameta v0.7.1
   Compiling proc-macro2 v1.0.24
error[E0658]: use of unstable library feature 'matches_macro'
```

I tried with nightly and stable rust.
Rustup is installed and fine.

This is a VM using Debian 10.11

What can I do ?

**Comment by Saecki** [comment]
It seems like your rust version is out of date. You could install rust using rustup  to get the latest release.

**Comment by pirona** [comment]
> It seems like your rust version is out of date. You could install rust using rustup to get the latest release.

Hello, thanks for your answer.  That's what I did : it solved my problem.

**Comment by lnicola** [comment]
I've seen Debian maintainers say the packaged `rustc` is in there to build the distro packages that require Rust, so they shouldn't be used for anything else.
