### ISSUE TITLE
What Audio library was used?

### ISSUE THREAD

**Issue by nednoodlehead** [agersant/polaris#173]
Does anyone know the library used to play music? I searched for all 'use' statements and saw nothing mentioning music, or audio.

**Comment by agersant** [comment]
Hello!

@mzagrabe is correct. The Polaris [web client](https://github.com/agersant/polaris-web) uses simple `<audio>` HTML tag, there is no library involved.
The [Android client]((https://github.com/agersant/polaris-android)) uses Exoplayer.
