### ISSUE TITLE
Playing aiff ?

### ISSUE THREAD

**Issue by mtsbh** [agersant/polaris#177]
Thanks for the great server, but I have one tiny issue. I can't play .aiff format files. Neither on web UI nor on the app. Is it not supported?

**Comment by lnicola** [comment]
Polaris uses Web Audio (the browser support) to play the files. I don't know if any browsers support AIFF (Safari might?).

**Comment by mtsbh** [comment]
```
17:58:01 [ERROR] [src\app\index\metadata.rs:76] Error while reading file metadata for '"***\\beckhäuser & emee - forror MST.wav"': NoTag: No tag chunk found!
17:58:01 [ERROR] [src\app\index\metadata.rs:76] Error while reading file metadata for '"***\\Bexu - Calatoria (Crihan remix).aif"': NoTag: No tag chunk found!
17:58:01 [ERROR] [src\app\index\metadata.rs:76] Error while reading file metadata for '"***\\Bezobrazity.mp3"': NoTag: reader does not contain an id3 tag
17:58:01 [ERROR] [src\app\index\metadata.rs:76] Error while reading file metadata for '"***\\Boncalo Denis - True Story - 02 Fuel to.wav"': NoTag: No tag chunk found!
```

Are these log errors because of that? No way of transcoding on the run also?

**Comment by lnicola** [comment]
I'm not the project author, but I think transcoding is out of scope. Is there any reason why you can't convert them to FLAC (or even WAV)?

**Comment by agersant** [comment]
Hello!

`aif` files can be indexed in the music collection, but as @lnicola said - playback capability depends on the browser you are using.

The errors you pasted indicate that the files listed don't have any metadata (artist, album, etc.) and thus cannot be indexed. 
Here is a working `aif` file that is part of the Polaris test suite: https://github.com/agersant/polaris/blob/master/test-data/formats/sample.aif?raw=true
