### ISSUE TITLE
Folder images not loading on polaris

### ISSUE THREAD

**Issue by anastergun** [agersant/polaris#179]
Started using polaris this week as a docker image and i`m loving it, also using the android app on my phone. Loved the way your program lists the directory tree so i can easily find the music i want to play.

Unfortunately, I am having a problem where the images cant load on my instance, it only stays as blank:
![image](https://user-images.githubusercontent.com/118664106/202898878-30c3e379-b39d-4514-8c5a-3415a5ce3187.png)

While checking the logs on my portainer, it seems that the aplication gets an internal error:

11:12:26 [ERROR] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/response.rs:57] Internal Server Error: Unspecified

11:12:26 [INFO] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 10.20.30.112:60083 "GET /api/thumbnail/YOUTUBE%2FDJ%20Hero%202%20Soundtrack%2F01%20-%20Just%20Dance%20vs.%20Ghosts%20'n'%20Stuff.mp3?pad=false&auth_token=1vWiUlAI8UtbOJnhY4bOtk15SsMZfjkLuNVMfGkZJwQDdtw1lX7sUlmFdGRbDjZ8WTK93Jnu2IqmC83LtEkbX9CUDPQ5TLpbY6CJYirvgjrdssoe6UUtW9c HTTP/1.1" 500 11 "http://10.20.30.100:1843/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.136330

11:12:26 [INFO] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 10.20.30.112:60083 "GET /api/browse/YOUTUBE%2FDJ%20Hero%202%20Soundtrack HTTP/1.1" 200 23914 "http://10.20.30.100:1843/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.010268

11:12:42 [INFO] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 10.20.30.112:60086 "GET /api/browse/YOUTUBE HTTP/1.1" 200 188 "http://10.20.30.100:1843/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.083324

11:12:42 [INFO] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:337] 10.20.30.112:60086 "GET /api/thumbnail/YOUTUBE%2FDJ%20Hero%202%20Soundtrack%2Ffolder.png?pad=false&auth_token=1vWiUlAI8UtbOJnhY4bOtk15SsMZfjkLuNVMfGkZJwQDdtw1lX7sUlmFdGRbDjZ8WTK93Jnu2IqmC83LtEkbX9CUDPQ5TLpbY6CJYirvgjrdssoe6UUtW9c HTTP/1.1" 500 11 "http://10.20.30.100:1843/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.098614

11:12:42 [ERROR] [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/response.rs:57] Internal Server Error: Unspecified

This it a print of the folder i'm trying to load the image:
![image](https://user-images.githubusercontent.com/118664106/202898986-f63e02cd-8439-4e27-8e9a-d956f6e4811a.png)

I`m currently running Polaris via docker as root on a Ubuntu Server 20.04.
FYI, only images are having this issue, the music plays normally on webUI and on the android app

**Comment by agersant** [comment]
Thank you for trying out Polaris and for the bug report!

The log snippet you posted indicates that your `folder.png` image was detected as album art, which is good. Most likely something is going wrong while trying to convert it to a thumbnail.

At the beginning of your `polaris` log, there should be a line that looks like this (with a different path of course):
```
23:16:11 [INFO] [src\main.rs:101] Cache files location is "C:\\Users\\agersant\\AppData\\Local\\Permafrost\\Polaris"
```
Can you make sure that `polaris` has permissions to create and read directories/files under this location? It is where downscaled album art thumbnails get saved and served from.

I am also working on improving error messages across the board to make issues like this easier to troubleshoot.

**Comment by anastergun** [comment]
Thanks for the support, i applied a chmod 777 on the folder where i save the polaris cache and it worked marvelous:

![image](https://user-images.githubusercontent.com/118664106/203046244-42ede117-769a-416d-b185-b5245d0c7dad.png)
