### ISSUE TITLE
Multiple Library Locations - Docker and Ubuntu

### ISSUE THREAD

**Issue by Teflon98** [agersant/polaris#185]
Greetings,

I'm using Docker.  I've tried using Symbolic links to the /music folder but it doesn't work.

Trying to add a path in the web interface doesn't seem to work either.

Is there a syntax in the web interface for SMB shares?

Thank you!

**Comment by Saecki** [comment]
There is [docker-polaris](https://github.com/ogarcia/docker-polaris), if that is of any help

**Comment by Teflon98** [comment]
> There is [docker-polaris](https://github.com/ogarcia/docker-polaris), if that is of any help

Thanks for the quick response: I've used that page and I have Polaris running.

The issue is adding a second music path.  Can the web interface add another location outside the machine?

Thanks again

**Comment by Teflon98** [comment]
Added a second volume map to the Docker setup:

  -v /mnt/AAAmusic:/music \
  -v /mnt/BBBmusic:/music2 \
  
  In the web interface, added 'music2' to Media Sources

**Comment by agersant** [comment]
Glad it worked out! 🥳
