### ISSUE TITLE
Two issues: permission denied when trying to run without sudo and unable to open database file with systemd

### ISSUE THREAD

**Issue by conquestace** [agersant/polaris#190]
1. LogFileCreationError("var/log/polaris.log", 0s { code:13, kind: PermissionDenied, message: Permission Denied })
2. .cargo/registry/src/github.com-1ecc6299db9ec823/r2d2-0.8.10/src/lib.rs:121] Unable to open the database file

are the two errors I got when systemd was trying to open polaris.

If I do sudo polaris, I can run it just fine, but yeah.

**Comment by agersant** [comment]
Hello,

It sounds like you did a system-wide install of polaris, which would explain why it is relying on directories that require admin permissions on your system. The [install process](https://github.com/agersant/polaris/blob/master/docs/SETUP.md#polaris-installation) also supports installing in XDG directories, which usually do not require elevated permissions.
