### ISSUE TITLE
Issue in detecting files

### ISSUE THREAD

**Issue by sbstrkt** [agersant/polaris#197]
Hi, and thanks a lot for Polaris.   

I am running through an issue very likely related to permissions. The files stored in the target folder do not show up. 

The test-data works fine, but none of the files from my own collection (.jpg .wav or .mp3 files) show up in the Music Collection. 

I changed the files permissions so they are similar to the test data to no avail:

`chmod 755 music_file.wav` and `chown -R 100:100 /my/polaris/data` did not work.

Maybe someone can point out to a solution. It would be appreciated.

**Comment by lnicola** [comment]
This is not related at all to Polaris, but you want:

 - directories to be 755
 - files to be 644
 - the owner to be you, or at least not an inexistent UID and GID

You can fix these with something like:

```sh
find /my/polaris/data -type d -exec chmod 755 {} \;
find /my/polaris/data -type f -exec chmod 0644 {} \;
chmod -R $(id -u):$(id -g) /my/polaris/data
```

Untested, and generally know it's a good idea to try understand commands given by random people from the Internet before running them.

**Comment by sbstrkt** [comment]
Hi @lnicola and thanks for your reply. 

To simplify the setup, I placed the test-data files, and some of my own files under `/home/user/music` (as per one of the unit tests)

I changed the files' and directorie's permissions recursively as indicated : 

```
find /home/user/music -type d -exec chmod 755 {} \;
find /home/user/music -type f -exec chmod 0644 {} \;
```  

And changed the ownership of the files and directories:

`chown -R $(id -u):$(id -g) /home/user/music`

However the behavior persists: I can only read the test-data files, and not my own.

**Comment by lnicola** [comment]
Do you get any log messages from Polaris? You can also `strace` it to see what fails.

**Comment by sbstrkt** [comment]
> You can also strace it to see what fails.

For `strace -u user -E=/home/user/music -p PolarisPID` I have this output:

`clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=10, tv_nsec=0}, 0x7ffc9f721fb0) = 0`

> Do you get any log messages from Polaris?

No. 

Since it is running behind nginx, there are some nginx logs which throw some suspicious errors,  but I can't find logs or error logs from Polaris.

**Comment by lnicola** [comment]
Try `sudo strace -fp PID`, then go to the Polaris settings and hit "Rescan library".

**Comment by sbstrkt** [comment]
Here is the log from strace: https://gist.github.com/sbstrkt/9be0461538ae2f6f25da30a18ff7f48e  

Just guessing, but *maybe* it is related to this error: `3808  newfstatat(AT_FDCWD, "/usr/local/var/lib/polaris/db.sqlite-journal", 0x7f709cc7ee10, 0) = -1 ENOENT (No such file or directory)`

Much appreciated.
`

**Comment by sbstrkt** [comment]
I tested other sources of audio, and the issue seems to be related to the audio file. 

This command fixed it:

`ffmpeg -i input.wav -ar 44100 -ac 2 -b:a 192k output.mp3`

Now the `.mp3` file is served, but the same track in `.wav` doesn't show up.   

@lnicola Thanks.

**Comment by lnicola** [comment]
WAV should be supported AFAICT: https://github.com/agersant/polaris/blob/master/src/utils.rs. You might want to reopen this.

But I suggest using FLAC, it's lossless and about twice as small as a WAV.

> Here is the log from strace

Sorry, I missed it, but the `db.sqlite-journal` error is fine, the journal file is transient (gets deleted at the end).

**Comment by Saecki** [comment]
From what I could read, there is no standard way of storing metadata in `WAV` files. The way Polaris and most other apps support it, is by reading an embedded id3 tag. Maybe your file has metadata stored some other way? If yes it might be worth it trying to support that too.
