### ISSUE TITLE
Linking error on Rust stable toolchain

### ISSUE THREAD

**Issue by ogarcia** [agersant/polaris#199]
Right now Polaris cannot be compiled with Rust stable because it gives a linking error at the end. Basically it is a reference error not defined by a dependency, you can see [more information in this issue](https://github.com/rust-lang/rust/issues/119883).

TL/DR:
Simply run `cargo update -p getrandom` to update your `Cargo.lock` and commit the changes to repository.

**Comment by agersant** [comment]
Thanks for the report! Fixed in c1abd8fe3b2cdfaddee520551bc27ef16f71473f and released in `0.14.1`.
