### ISSUE TITLE
Inquiry Regarding Bandwidth Limitation in Polaris Project

### ISSUE THREAD

**Issue by Simisled** [agersant/polaris#205]
Hy There,

I am reaching out to inquire about a potential limitation I've encountered while using the Polaris project for streaming audio services.

Upon scanning my files, I've noticed that the maximum throughput I can achieve is 100Mb/s. This limitation has posed some challenges for my intended use case. I am curious to know if it's feasible to modify or remove this bandwidth restriction within the Polaris project.

Could you kindly provide some insights into whether such modifications are possible or if there are alternative approaches to achieving higher throughput within the project?

Thank you for your attention to this matter. I look forward to your response and appreciate your efforts in developing the Polaris project.

Best regards,
Simis

**Comment by agersant** [comment]
Related discussions:
https://github.com/agersant/polaris/pull/96
https://github.com/agersant/polaris/pull/86 (older)

Polaris indexing is already faster than its competitors (last I checked) and currently has no known way of becoming faster.
