### ISSUE TITLE
[Feature request]: Option to avoid resampling/ have uncapped bitrate

### ISSUE THREAD

**Issue by marek-lach** [agersant/polaris#209]
I just noticed there's no bitrate information about the file currently being played anywhere in the interface, but more specifically, I would wish to know that the files are not being resampled by `Polaris`.

Thank you for considering this feature.

**Comment by lnicola** [comment]
There's no resampling done by Polaris, it uses HTML Audio to play the original files.

**Comment by dechamps** [comment]
…and you can verify that by using whatever developer tools your browser offers (e.g. "Page Info" in Firefox). From there you can get the URL of the actual audio file your browser is fetching from Polaris. You will notice it is indeed the original file, completely untouched. In other words Polaris is "bit-perfect". It also means that if your Polaris library contains FLAC files, they will be streamed as FLAC (and the FLAC decoding is done by your browser).

**Comment by marek-lach** [comment]
> …and you can verify that by using whatever developer tools your browser offers (e.g. "Page Info" in Firefox). From there you can get the URL of the actual audio file your browser is fetching from Polaris. You will notice it is indeed the original file, completely untouched. In other words Polaris is "bit-perfect". It also means that if your Polaris library contains FLAC files, they will be streamed as FLAC (and the FLAC decoding is done by your browser).

Ah, great stuff! Good to know.
