### ISSUE TITLE
Polaris unable to scan media library

### ISSUE THREAD

**Issue by agottschling** [agersant/polaris#21]
Every time I try to scan for media, the button just turns red and says "Error :(". 
The error message in the log is as follows: 
```
Error while writing to index command buffer: sending on a closed channel
Skipping DDNS update because credentials are missing
Skipping DDNS update because credentials are missing
Starting up database
Database file path: /home/media/.local/share/polaris/db.sqlite
Mounting API on /api
Beginning library index update
Mounting static files on /
Starting up server
Starting up UI (headless)
Skipping DDNS update because credentials are missing
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
My media is on a NAS, and I've tried everything. Accessing it through a UNC path on both windows and linux, Mounting it as a network drive on windows, mounting it into a folder using CIFS on linux. I'm totally out of ideas.  
PS. I know the NAS is accessible because emby can see it using any of the above methods on the exact same computer.

**Comment by agersant** [comment]
Thank you for the report!

A few questions:
- Can you post the full log?
- Does it still happen after restarting polaris (or the computer where it runs)?

**Comment by agottschling** [comment]
Hey @agersant,
That's the log file in its entirety. Only different between that and the file on disk, is that I isolated it from the subsequent restart of Polaris. 
To answer your second question, restarting Polaris has no effect.

**Comment by agottschling** [comment]
If it would help you, I can do a TeamViewer session or something with you. Just let me know

**Comment by agersant** [comment]
Thank you!
I'll take a look locally first and keep you posted. The crux of the error seems to be the very first line of the log. Polaris uses a Rust construct called a channel to communicate with the thread responsible for indexing the collection (and telling it to begin work). In this case, it looks like the channel is immediately in a unusable state.

**Comment by agottschling** [comment]
Whelp, no idea what I did, but it's working now. Only downside is that I can't for the life of me figure out how to make it a systemd service. But that's for another issue.

**Comment by agersant** [comment]
I'll make the error handling a little cleaner around this, but I'm unsure how it happened in the first place.

Regarding systemd, here is the script I use whenever I need to re-image my Raspberry Pi which runs Polaris. One of the things it does is setup Polaris as a systemd service:
https://gist.github.com/agersant/1c3bac006b4201fcf3bf4c857c56067c

**Comment by agottschling** [comment]
Thanks, but systemd is complaining about that PID file not being readable. Any ideas?
