### ISSUE TITLE
Translations to other languages

### ISSUE THREAD

**Issue by anastergun** [agersant/polaris#210]
Greetings.

Firstly and foremost, congratulations for the project, I've been using it for more than a year and it works wonders.

After seeing a video from Chris Titus saying that we should help open source projects, i was wondering how i can help polaris and noticed that the project is only in English.

I would like to help translating the project to other languages (I can help with Brazilian Portuguese and Spanish translations).
 But, i don't know how to start.

BTW, thanks for the attention.

**Comment by agersant** [comment]
Hello! Thanks for taking the time to write this, hearing about other people using Polaris always makes my day!

Unfortunately Polaris currently has no support for localization so the translating work would be wasted. Thank you very much for offering, and for deciding to help open source projects ♥.
