### ISSUE TITLE
Use other streaming platform as source

### ISSUE THREAD

**Issue by hatch01** [agersant/polaris#214]
It would be realy great to be available to connect to other platforms like spotify, YouTube music, deezer and use them as music sources.
In my idea, the Polaris server would be a proxy for all those platform while being able to easily create playlist with one music from Spotify, then a local music, then a yt music song.
Caching those music would also be useful I think.

**Comment by doudyy** [comment]
@hatch01 you might want to check out Openwhyd. It's a music curation platform that allows you to gather tracks from various sources like YouTube, SoundCloud, and others into a single playlist. This way, you can create a diverse playlist with tracks from multiple platforms, all in one place.

However, Openwhyd doesn’t provide caching capabilities, so the music streams directly from the original sources without being stored locally.

https://github.com/openwhyd/openwhyd.git
