### ISSUE TITLE
linux install error

### ISSUE THREAD

**Issue by Lap1acian** [agersant/polaris#216]
In rust latest version, polaris install method occur error. maybe need specific version of available rust version or update script.

**Comment by agersant** [comment]
Thanks for reporting the issue. What is the error message you are seeing?

If it looks anything like [this](https://github.com/agersant/polaris/pull/213), you can try installing Polaris 0.14.3 which I just published.

**Comment by Lap1acian** [comment]
Thank you. It seems that the issue with the time was resolved with your guidance. Although there was one warning, everything appears to be functioning normally. For future development reference, I'm attaching the warning log below. Have a great day :)
![Uploading Screenshot 2024-09-30 at 8.52.34 PM.png…]()
