### ISSUE TITLE
Web frontend fails to load

### ISSUE THREAD

**Issue by jdm** [agersant/polaris#224]
I cloned polaris-web and ran polaris with the web directory pointing at the repo. When I load localhost:5050 in either Firefox or Chrome, I see the following error:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "video/vnd.dlna.mpeg-tts". Strict MIME type checking is enforced for module scripts per HTML spec.
```
This happens when we fetch `src/index.ts`, which hits [this service](https://github.com/agersant/polaris/blob/d06ad07f512139b3662da1e84ba9ef29097376ba/src/service/actix.rs#L38-L41). actix-files appears to rely on mime_guess to determine what content type to return when service files like this, and mime_guess associates .ts with a video subtitle format: https://github.com/abonander/mime_guess/blob/805964fb54871f0154ee155bf21729b77ffd4a1c/src/mime_types.rs#L1257

How does this run correctly for anybody else?

**Comment by agersant** [comment]
Hi. It sounds like you're trying to use the source code of polaris-web as the client. It needs to be compiled in order to work.

You can execute `npm run production` in the cloned polaris-web directory to produce a `/dist/` directory that has the compiled web client which Polaris can serve.

**Comment by jdm** [comment]
Ah, yes, that explains it. Thanks!
