### ISSUE TITLE
upgrade to rust-openssl `0.10`

### ISSUE THREAD

**Issue by makmm** [agersant/polaris#24]
rust-openssl `0.9` doesn't work with openssl `1.1+`. could you please upgrade it to `0.10+` so it works on debian `sid`?

related issue: https://github.com/sfackler/rust-openssl/issues/987

**Comment by agersant** [comment]
Thanks for the report. This is now fixed in 37a4521e15cec21abbc7a048f860755da38b4e3f.

**Comment by makmm** [comment]
thanks <33

**Comment by makmm** [comment]
@agersant when is the next release? or can i just clone the repo and run make install?
