### ISSUE TITLE
nothing happens when running `~/.local/bin/polaris/polaris`

### ISSUE THREAD

**Issue by makmm** [agersant/polaris#25]
nothing logs, it just quits. like this:
```
void@voidcoinminer:~/polaris/polaris/release$ ~/.local/bin/polaris/polaris 
void@voidcoinminer:~/polaris/polaris/release$
```

compiled from `master` branch.

**Comment by agersant** [comment]
By default the Polaris process forks and writes logs under ~/.local/share/polaris.

To get console output, you an run in the foreground with the -f flag.

**Comment by makmm** [comment]
polaris-web wasn't being downloaded. maybe add instructions on how to dl submodules?

**Comment by makmm** [comment]
(i checked logs and it gave not-found errors)

**Comment by makmm** [comment]
(and the server worked but it just gave a blank page)
