### ISSUE TITLE
Cannot compile latest version 0.9.0

### ISSUE THREAD

**Issue by ogarcia** [agersant/polaris#27]
In Linux, doing `cargo build --release` I have the following error.
```
   Compiling notify v4.0.9
   Compiling h2 v0.1.16
   Compiling id3 v0.2.5
   Compiling devise_core v0.2.0
error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:2:1
  |
2 | #![feature(crate_visibility_modifier)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:3:1
  |
3 | #![feature(concat_idents)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `devise_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I'm using cargo version 1.31.1 and rust 1.31.1.

**Comment by agersant** [comment]
Thank you for the report! Because of its newly added dependency on Rocket, Polaris now requires a Rust compiler from the nightly channel.

If you want to keep your stable version of the Rust compiler and use nightly only to compile Polaris, you can run:
- `rustup install nightly`
- `cargo +nightly build --release`

I just updated the README and release notes accordingly.

**Comment by ogarcia** [comment]
This is bad because Alpine Linux do not have `rustup` :sob: and cannot update the docker image. But don't worry, can wait for rust package update in Alpine repository.

**Comment by agersant** [comment]
If you want to follow the progress of Rocket towards stable rust, you can keep an eye on this issue: https://github.com/SergioBenitez/Rocket/issues/19

The latest Rocket development update (https://rocket.rs/v0.4/news/2018-12-08-version-0.4/) announced that this should be completed for their next major release.
