### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by IrosTheBeggar** [agersant/polaris#28]
I found this project while checking out the awesome selfhosted list.  I'm working on my own [music streaming server](https://github.com/) and noticed we we're working towards similar goals. 

Would you be interested in collaborating on some projects in the future?  I noticed there are several devs working on similar projects, and if we worked together we could get a lot farther.  I'm open to ideas for project to collaborate on, so let me know if you're interested.

**Comment by agersant** [comment]
Hi there!
Thank you for reaching out. You are right, I do see a lot of similar priorities between mStream and Polaris. I am interested in potential collaborations, with two caveats:
- Not sure how code could possibly be shared considering our tech stacks are fairly different
- Polaris is a hobby project so I don't want to make any commitments in terms of results or regularity of my time investment

Cheers!
