### ISSUE TITLE
Error after installation and startup: "The program can't start because SSLEAY32MD.dll is missing from your computer..."

### ISSUE THREAD

**Issue by waut3r** [agersant/polaris#3]
As the title says, the program starts with an error: "The program can't start because SSLEAY32MD.dll is missing from your computer. Try reinstalling the program to fix this problem."

I'm on Windows 10, running version 1607. This is with Polaris 0.2.0.

**Comment by agersant** [comment]
Thanks for the report! I just fixed this in release 0.3.0, can you confirm this works for you?

Please uninstall version 0.2.0 before installing 0.3.0.
