### ISSUE TITLE
Support embedded album art

### ISSUE THREAD

**Issue by Darksecond** [agersant/polaris#34]
Most music formats can have album art embedded in the music file themselves. It would be great if it was supported as it's used a lot these days.

**Comment by Saecki** [comment]
I would like to give this a try and I think there are two general options.
1. Extract the images while indexing and store them in the `thumbnail` or a separate `original artwork`(or similar) directory.
2. Indicate in the `Song.artwork` that there is an embedded artwork and read that to generate the thumbnails.

What would be the preferred way of doing this?

**Comment by agersant** [comment]
Thanks for giving this a shot!

I think approach 2 is my preference. Approach 1 could take up a lot of disk space, and is difficult to maintain efficiently on each re-index (image content can change, user can remove images from disk manually, etc.). In approach 2, I would also recommend using the existing `artwork` column (in the `directories` and `songs` tables) to store the path to the music file containing album art. The code generating thumbnails would then be updated to:
- Differentiate image files from audio files
- If applicable, extract the artwork from the audio file to generate the thumbnail

**Comment by agersant** [comment]
Thank you @Saecki for this very useful addition <3
