### ISSUE TITLE
Indexing performance improvements

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris#35]
What the title says. I'd like to test Polaris, but it's a bit slow at scanning my media library. Being able to share the library with `mpd` would be really nice.

**Comment by lnicola** [comment]
Unfortunately, there's no great way to implement this. `mpd` itself can't stream the songs, and if queried it will not return the full path of files. Some solutions here would be to:

- tell Polaris where the library root is
- use a network share with `mpd` and implement support for that in Polaris

Neither approach seems great :-(.

**Comment by agersant** [comment]
I think I would rather focus on improving the speed of media library scanning instead. Do you have some metrics on timing and hardware utilization for Polaris vs mpd?

**Comment by lnicola** [comment]
Another solution is to directly read `mpd`'s database :smile:.

Regarding the scanning speed, `mpd` can skip unchanged files. On my library it takes about 10 seconds on a cold cache and is instant with a warm cache. Polaris takes 265 seconds.

**Comment by lnicola** [comment]
Note that while I haven't been able to get it working properly, `mpd` also has support for `inotify` and friends, in theory making manual database rescans unnecessary.

**Comment by agersant** [comment]
Replacing scans is covered here: https://github.com/agersant/polaris/issues/5

Skipping unchanged files is a good idea (and an action item for this issue).

I am surprised mpd is so much quicker for you - on my system the Polaris scan is barely longer than the time it takes to traverse the file structure. Is your mpd configured to harvest as much metadata as Polaris from the files (including duration from VBR mp3)? What do IO and CPU usage look like during a Polaris scan?

**Comment by lnicola** [comment]
On a first impression, Polaris seems to first check if the files still exist (`stat`), then goes over them, checks again for existence, opens them, and reads around 10 KB or so, sequentially. On a FLAC I see the following reads: 4, 4, 2, 4, 32, 32, 64, 128, 256, 172, 4, 32, 32, 64, 40, 4, 32, 32, 64, 128, 256, 512, 1024, 2018, 3968.

`mpd` checks the files for existence, then walks the directory tree looking for `.mpdignore` files and doing a `readlink`, `stat` and `access` on each song (which seems redundant).

When it does read a file, it makes three reads of 40960, 62639 and 40960 bytes (for an MP3).

> Is your mpd configured to harvest as much metadata as Polaris from the files (including duration from VBR mp3)?

I don't know if it can do that, but I don't particularly care.

**Comment by agersant** [comment]
I took a fairly in-depth look at this today.

- For FLAC, I found that the metaflac dependency wasn't using a buffered reader and made the many syscalls you measured. I just forked it and switched to a buffered reader which should help a lot. Would like to hear measurements on your collection as I don't have enough disk space to run large FLAC samples.
- I thought there was time to be saved by looking for files matching the artwork pattern without an additional directory traversal, but that turned out to be negligible in my tests (due to OS file caching).
- For mp3, we usually do two reads of 8KB and the second one has negligible duration (due to caching again) so not much to be won here.
- Everything outside of metadata parsing (bookkeeping, DB access, etc.) was also negligible

**Comment by lnicola** [comment]
Thanks, that probably helps. Scanning my library now takes 267 seconds on a very cold cache and 13 seconds on a very warm cache (the best case). I previously reported 265 seconds, so I'll try to see what happens after it runs for a couple of days.

**Comment by agersant** [comment]
That's a good point. I can try profiling on my raspberry pi next time I investigate, that should be a fairly good representation of a low-end machine.

**Comment by lnicola** [comment]
A couple more:

```
# old version
polaris[13383]: 14:34:10 [ INFO] polaris::index: [src/index.rs:452] Library index update took 271 seconds
polaris[13383]: 07:14:05 [ INFO] polaris::index: [src/index.rs:452] Library index update took 267 seconds
polaris[13383]: 23:54:07 [ INFO] polaris::index: [src/index.rs:452] Library index update took 268 seconds
polaris[13383]: 16:34:13 [ INFO] polaris::index: [src/index.rs:452] Library index update took 275 seconds
polaris[13383]: 09:14:04 [ INFO] polaris::index: [src/index.rs:452] Library index update took 266 seconds
polaris[13383]: 01:52:38 [ INFO] polaris::index: [src/index.rs:452] Library index update took 179 seconds

# new version
polaris[1733]: 10:37:29 [ INFO] polaris::index: [src/index.rs:464] Library index update took 263 seconds
polaris[1733]: 03:17:31 [ INFO] polaris::index: [src/index.rs:464] Library index update took 265 seconds
```

Seems unfortunate :sweat_smile:.

**Comment by agersant** [comment]
Yeah it looks like this change was a complete non-factor in your case.

**Comment by agersant** [comment]
Renamed issue to match where the discussion lead.

**Comment by agersant** [comment]
Closing this as a result of https://github.com/agersant/polaris/pull/59
