### ISSUE TITLE
Issue on initial setup

### ISSUE THREAD

**Issue by skrzepto** [agersant/polaris#42]
I took the latest git branch and ran 

```
cargo +nightly build
./target/debug/polaris -p 8182 -f
```

When ever I go visit `localhost:8182` in the browser I get 500 internal server error. I have a feeling there might be a config I am missing.

**Comment by lnicola** [comment]
You might need to pass it the path to the Web UI files. They're in a git submodule:

```
git submodule update --init --recursive --progress
cargo run -- -w web
```

or something like that.

Of course, it would help if you pasted the relevant parts of the log.

**Comment by skrzepto** [comment]
Yup `-w web` was my missing configuration which I just started to read about in https://github.com/agersant/polaris/blob/master/CONTRIBUTING.md

Thank you for the quick response.
