### ISSUE TITLE
Song names not showing

### ISSUE THREAD

**Issue by skrzepto** [agersant/polaris#43]
I usually pull music from youtube-dl and the file list is coming up blank. Maybe consider falling back to filename?
![image](https://user-images.githubusercontent.com/3166193/62726848-c9704580-b9dd-11e9-9624-1998a3e3accb.png)

**Comment by lnicola** [comment]
This sounds like a good idea, but note that you can also use `youtube-dl --add-metadata` to fill those in.

**Comment by agersant** [comment]
Oof, that looks pretty horrible. Will definitely fix this before next release. Thank you!

**Comment by agersant** [comment]
Fixed in https://github.com/agersant/polaris-web/commit/41102b7ae8f31e28200d6c4ddda1db765004c85a
