### ISSUE TITLE
not compiling on macOS

### ISSUE THREAD

**Issue by andrewbanchich** [agersant/polaris#44]
Just tried compiling 0.10.0 on macOS and it fails with:

```
~/D/polaris-0.10.0 > make install
cargo build --release
   Compiling migrations_internals v1.4.0
   Compiling rocket v0.4.0
error[E0432]: unresolved import `std::boxed::FnBox`
 --> /Users/andrewbanchich/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.0/src/fairing/ad_hoc.rs:2:5
  |
2 | use std::boxed::FnBox;
  |     ^^^^^^^^^^^^^^^^^ no `FnBox` in `boxed`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `rocket`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] Error 101
```

**Comment by agersant** [comment]
The dependencies in the latest release are a bit out of date compared to the recent versions of Rust nightly. @lnicola  recently updated the dependencies so building from master instead should work.

The easiest way to do this is:
- Clone this repository
- Run `build_release_unix.sh` from the top level of the repository
- Resume regular setup instructions using the tarball which you now have under the `/release` directory

Please let me know how this goes, I don't know of other macOS users (outside of CI unit tests).

**Comment by andrewbanchich** [comment]
That worked! Thanks
