### ISSUE TITLE
order by track number

### ISSUE THREAD

**Issue by gilescope** [agersant/polaris#45]
It's pretty good at playing music (using it via docker on OSX).

Would be really great if it ordered by track number please.

**Comment by gilescope** [comment]
Currently the 'default' ordering seems pretty arbitrary on my system.

**Comment by agersant** [comment]
The Polaris web player already sorts songs by track number when possible.

What format do you use to store music? Does it have proper metadata?
Can you add a screenshot of what you see?

**Comment by agersant** [comment]
Closing inactive issue
