### ISSUE TITLE
Pear requires a nightly or dev version of Rust. Installed version is: 1.38.0 (2019-09-23). Minimum required: 1.31.0-nightly (2018-10-05

### ISSUE THREAD

**Issue by nephaste** [agersant/polaris#51]
I am trying to bring Polaris on Qnap NAS servers but 

Stuck on error on compilation

   Compiling app_dirs v1.2.1
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rustc_version v0.2.3
   Compiling log v0.3.9
   Compiling want v0.0.6
   Compiling lock_api v0.1.5
   Compiling crossbeam-channel v0.3.8
   Compiling tokio-executor v0.1.6
error: failed to run custom build command for `pear_codegen v0.1.2`

Caused by:
  process didn't exit successfully: `/SRC/.MYSCRIPT/tmp3/target/release/build/pear_codegen-57d5be294dbebc7c/build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.38.0 (2019-09-23). Minimum required: 1.31.0-nightly (2018-10-05).
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.2/build.rs:31:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

any help is welcome

cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)

rustc --version
rustc 1.38.0 (625451e37 2019-09-23)

**Comment by lnicola** [comment]
Did you install `rust` via `rustup`? If so, try `rustup toolchain install nightly`, then `rustup toolchain default nightly`.

**Comment by nephaste** [comment]
installed rust + cargo long time ago on my ubuntu... and did a rustup update...

weird my version is upper than the required one... 

i am applying your command and will tell you

**Comment by lnicola** [comment]
> weird my version is upper than the required one...

It's not weird. Nightly is indeed newer than beta and stable, but it allows you to use features that haven't yet been _stabilized_ in the language. Since the web framework that Polaris uses needs some of those nightly feature, it won't build on any stable version, no matter how high, until changed to not need those features any more.

**Comment by nephaste** [comment]
Thanks for info..
second seems not been accept

rustup toolchain default nightly
error: Found argument 'default' which wasn't expected, or isn't valid in this context

USAGE:
    rustup toolchain <SUBCOMMAND>

For more information try --help

**Comment by lnicola** [comment]
Sorry, that should have been `rustup default nightly`.

**Comment by nephaste** [comment]
thanks a lot ... it works
