### ISSUE TITLE
memory allocation crash when indexing music.

### ISSUE THREAD

**Issue by McSpidey** [agersant/polaris#52]
I've just tried building this using the current source and it seems to run ok, indexing the music library (I can see it looking at files via Resource Monitor) until eventually it gives this error and crashes.
"memory allocation of 18446744073709551584 bytes failed"

**Comment by agersant** [comment]
That's a very new class of bug. I suspect this is an issue while attempting to read information within a specific file - is your resource monitor indicating that it's always failing in the same spot?
If the resource monitor makes it hard to tell, you could add some (very spammy) logging around here: https://github.com/agersant/polaris/blob/77a1e86f8482ae272e5fc26367cc1a4fbf0cf833/src/index.rs#L297 to see which files we are hitting.

**Comment by McSpidey** [comment]
I can confirm it does stop around the same place every time.  Thanks for the pointer on where to add the logging, I'll test that when I get a chance.

**Comment by McSpidey** [comment]
I've confirmed it is specific files that trigger this and the issue is reproducable just by setting Polaris to scan a folder containing them and triggering the scan.

Here's one: (old MP3 version of a music track from a Megadrive game) https://drive.google.com/open?id=1vRwmEeSYTyLpkt99cNhn6wF93LqHdb5m

Error: memory allocation of 18446744073709551609 bytes failed

**Comment by agersant** [comment]
Thanks, that was very helpful! As suspected, this file is lightly corrupted and breaks most code that tries to read through it (including foobar2000 and the Polaris web player). I fixed the code so this file can be indexed and played without major error.

Polaris fix here: 1a768c4c263992831d23a38d9749b235c4d02d04
Actual fix here: https://github.com/agersant/mp3-duration/commit/3308bb09bb9a8bf237ba559eaf2cfae33fea432b
