### ISSUE TITLE
Add a sign-out button to the web UI

### ISSUE THREAD

**Issue by agersant** [agersant/polaris#55]
This should:
- Clear the `username` and `admin` cookies client-side
- Re-route to /auth
- Delete the session on the server

**Comment by agersant** [comment]
Does either of these locations look reasonable?

Bottom left corner:
![bottom_left](https://user-images.githubusercontent.com/817256/102194241-ed655600-3e71-11eb-8778-650c7ef80bec.PNG)

Preferences panel:
![settings](https://user-images.githubusercontent.com/817256/102194245-edfdec80-3e71-11eb-8e22-127ea2ca97b6.PNG)

**Comment by agersant** [comment]
cc @ahxxm who may care about this

**Comment by agersant** [comment]
And @lnicola, I think you requested this originally

**Comment by ahxxm** [comment]
I'm ok with both, didn't expect myself to sign out anyway.....

**Comment by agersant** [comment]
Shipped in release 0.13

**Comment by lnicola** [comment]
I don't think it was me. I slightly prefer the first one, but it doesn't matter too much.

**Comment by agersant** [comment]
Lucky, that's the one I implemented!
