### ISSUE TITLE
MP4/m4a support

### ISSUE THREAD

**Issue by wezm** [agersant/polaris#70]
I see that in [utils::get_audio_format](https://github.com/agersant/polaris/blob/a05c838c5b2aeb447ea6586bd1ef002461544327/src/utils.rs#L48) there is a variant for MP4 but in [metadata::read](https://github.com/agersant/polaris/blob/312eb15a2b9104184bdb9112f287a1f505ae96d3/src/index/metadata.rs#L28) it is not handled.

I'm creating this issue to track support for MP4 files. It seems that what's missing is the ability to read the meta data from such files. I may have a go at implementing it since a large part of my library is m4a.

**Comment by rayrrr** [comment]
I am going to give this a try. Hoping that https://github.com/Saecki/rust-mp4ameta does the trick for a functioning PR.

**Comment by rayrrr** [comment]
@wezm @agersant have a look at this PR when you get a chance. Rocking out to my M4As via Polaris as I type!

**Comment by rayrrr** [comment]
Juicy links:

- https://mutagen.readthedocs.io/en/latest/api/mp4.html
- http://atomicparsley.sourceforge.net/mpeg-4files.html

**Comment by rayrrr** [comment]
Shout out to @Saecki, the author of the other crate. They found and fixed the bug and published a version-bumped crate for us already. https://github.com/Saecki/rust-mp4ameta/issues/1 Almost there!

**Comment by rayrrr** [comment]
Update: still working out issues with the mp4ameta crate with my real-world m4a collection. See https://github.com/Saecki/rust-mp4ameta/issues/2 for details.

**Comment by rayrrr** [comment]
Once again, @Saecki has fixed the bug and bumped the crate version, so now it is finally working for real! #82 is updated with the latest version and PR changes. Thanks for your patience.
