### ISSUE TITLE
Files won't list if a collection name has a space

### ISSUE THREAD

**Issue by rmNULL** [agersant/polaris#73]
### Steps to Reproduce the behavior

1. Visit Setting > Collection 
2. Under **Music Sources**  
set name to anything followed by a trailing space.
3. Visit Music collection, click on  previously selected name,
it wont load the music collection as it should.
The problem i see is it fails to encode space as %20.
manually entering %20 into the url after the name loads the directory.

The program version is `0.11.0`  built from tar.gz in the Release page.

**Comment by agersant** [comment]
Thank you for the good repro steps, shouldn't be too hard to fix for next version (no ETA though).

**Comment by agersant** [comment]
Turns out this did not happen on latest. I assume I fixed this at some point in the great rewrite of the web client which just shipped in 0.12.
