### ISSUE TITLE
Standardize filenames and version names in releases 

### ISSUE THREAD

**Issue by ogarcia** [agersant/polaris#76]
Until version 0.11.0 version names start with a `v`, since 0.12.0 the `v` was removed, not is a big problem, but breaks automations.

With assets names is the same: `polaris-0.11.0.tar.gz` `Polaris_0.12.0.tar.gz`.

I think that you must choose one format and use it from now :wink:

**Comment by agersant** [comment]
Sorry for the inconvenience.

Version 0.12 is the first release using the new automated release CI flow (instead of me running scripts of my computer), which unified the naming between Windows and Linux artefacts. Future releases should all be consistent with 0.12!
