### ISSUE TITLE
Docker version?

### ISSUE THREAD

**Issue by mbirth** [agersant/polaris#8]
I'd love to have a self-contained Docker image of Polaris to run on my Synology. I've found a [Rust base image](https://hub.docker.com/_/rust/) but as I don't know Rust, I'm missing the next steps to make it work.

It would be awesome if you could offer an image at some point in the future.

**Comment by agersant** [comment]
Thank you for the suggestion! I am a bit unfamiliar with docker or containers in general but maybe with our knowledge combined we can get somewhere.

The Rust Docker image you found takes care of installing the Rust toolchain so the next logical steps would be:

- Cloning the Polaris repository to the local filesystem (something like `git clone https://github.com/agersant/polaris/tree/v0.6.0`)
- Compiling Polaris. From the cloned project directory: `cargo build --release`. This will produce an executable in the project directory under target/release/polaris
- There are two options that may be important when running the executable:
1. We need to tell Polaris where the files for the web client are. By default, it will look for them in ~/.local/share/polaris/web. Instead, we can use the `-w some/path` option to point to the directory that has the files. The correct directory is /web in the project repository. Note that the log file and thumbnails will still go to ~/.local/share/polaris/, there is no option to customize those.
2. Polaris writes settings (user accounts, etc.) and the index of the collection in a database. By default, that database resides in ~/.local/share/polaris/db.sqlite. This can be overridden using the `-d some/path/db.sqlite` option.

The container instance will also need access to your music files somehow but I imagine Docker has a way to expose real directories to containers.

Let me know how this goes or if you need more help!

**Comment by ogarcia** [comment]
Hi @mbirth and @agersant 

I build a Docker of polaris, the code is [here in GitHub](https://github.com/ogarcia/docker-polaris) and the image is in [Docker Hub](https://hub.docker.com/r/ogarcia/polaris/) and [Quay](https://quay.io/repository/ogarcia/polaris).

There is an issue in automatic builds of Docker Hub and the build of containter is blocked since yesterday. I think that the problem will be solved soon, but in meantime you can get the container form Quay with following command.
```
docker pull quay.io/ogarcia/polaris
```

**Comment by agersant** [comment]
Thank you so much @ogarcia !
I added a note in the Polaris readme pointing to your repository for people who want to run Polaris within docker.
