### ISSUE TITLE
gapless playback / crossfade options

### ISSUE THREAD

**Issue by rayrrr** [agersant/polaris#83]
"Gapless playback" and crossfade between tracks are common options in similar software for e.g. live albums, vinyl rips, etc.

Can we add those?

**Comment by agersant** [comment]
This is a very desirable feature but there isn't much to do about it server-side.

I do have a long-standing ticket (issue number 1!) for it on the `polaris-web` repo: https://github.com/agersant/polaris-web/issues/1
It's a pretty high-effort feature so it has never made it to the top of my priorities but I do plan to do it one day. I'll close this ticket in favor of the `polaris-web` one. Note that the same can of worms also exists for the Android client.

**Comment by VlaK0r** [comment]
Hello!
Thank you for your hard work!

I agree that this is a very popular feature. I would like to hear its implementation.
For a web client, this feature is missing from almost all similar projects. But for the android client, it is present in almost everyone.

**Comment by agersant** [comment]
On Android, the underlying playback library does support gapless playback, but the playback sure doesn't sound gapless to me at the moment. I just opened a new ticket to track this work: https://github.com/agersant/polaris-android/issues/55

I will be working on the Android client in a few weeks to make it compatible with the next big release, I'll try to take a look into this while I'm there.

**Comment by VlaK0r** [comment]
> On Android, the underlying playback library does support gapless playback, but the playback sure doesn't sound gapless to me at the moment. I just opened a new ticket to track this work: [agersant/polaris-android#55](https://github.com/agersant/polaris-android/issues/55)
> 
> I will be working on the Android client in a few weeks to make it compatible with the next big release, I'll try to take a look into this while I'm there.

Thank you for the good news.

**Comment by agersant** [comment]
I'm sorry to report the ticket above will stay open for now :(

I reviewed the relevant `polaris-android` code and tried all permutations of the relevant options I have with no success.
