### ISSUE TITLE
Directories are sometimes empty until refreshed

### ISSUE THREAD

**Issue by stukkat** [agersant/polaris#95]
Windows 10
Polaris 0.12.4

Sometimes opening a directory will show it as empty. If I refresh the page it will display the files contained within,
but every now and again they will vanish again. This can happen in any folder, there does not seem to be any particular pattern to it.

**Comment by agersant** [comment]
I think this is the same thing as https://github.com/agersant/polaris/issues/90 (see my comment there for extra context). I have also noticed this many times on my own Polaris deployment. Specifically in this case, it's the result of the fetch for a directory's content that is getting dropped.

Keeping open until there is a solution (most likely after Rocket 0.5 ships). Will dupe future similar issues against this one.
