### ISSUE TITLE
0.12.4: "Vorbis bitstream header decode problem" and ignoring Opus files

### ISSUE THREAD

**Issue by NekoAlosama** [agersant/polaris#98]
All of my music are in Opus files with the .ogg extension (pseudo-extension for software compatibility, some software doesn't recognize .opus but does recognize .ogg and uses the right codec), so I expected them to work to some extent on Polaris. According to the polaris-cli.exe logs, all of the .ogg files create the following error:
```
hh:mm:ss [ERROR] [src\index\metadata.rs:41] Error while reading file metadata for '"C:\\{music}\\{song}.ogg"': Vorbis bitstream header decode problem
```
I'm assuming that this is because there are different functions for reading tags on .ogg and .opus files, so it brought up an error. Then I decided to test on one file by replacing the .ogg extension with .opus to see if it would work. However, **the file was ignored when I indexed the library.**

**Comment by vvrein** [comment]
Hi! Try to compile the latest polaris-server from the master branch. I'm successfully play opus files with latest polaris.
Also, try to download opus file like this: 
(it works for me)
```
youtube-dl -f 251 --extract-audio --audio-format opus "https://www.youtube.com/watch?v=zzzzzzzzzzz"
```

**Comment by NekoAlosama** [comment]
I've finally compiled the master build, and the .opus files are now detected. Sucks that .ogg is restricted to Vorbis on Polaris, though.

**Comment by agersant** [comment]
I just took a look at this and this behavior matches the official format specification by Xiph.org:

> .ogg applies now for Vorbis I files only

Full document: https://wiki.xiph.org/index.php/MIME_Types_and_File_Extensions

**Comment by NekoAlosama** [comment]
"¿Por qué no los dos?"
Guess I'm going to have two copies of my music library, one in .ogg and the other in .opus :P

**Comment by agersant** [comment]
I would recommend opening issues with the maintainers of the software that does not recognize opus files, they are the one not following standards.

**Comment by NekoAlosama** [comment]
@agersant I've learned something and was reminded of this thread. Apparently, Android didn't support the `.opus` extension until Android 10. That's why I needed the `.ogg` pseudo extension for it.

Ah well, at least my beginner Rust skills can at least create a solution that builds (although it is super ugly). Plus, with my current method, I'd have to add another match block if I wanted to add Ogg FLAC.
```
pub fn read(path: &Path) -> Option<SongTags> {
	let data = match utils::get_audio_format(path) {
		Some(AudioFormat::APE) => Some(read_ape(path)),
		Some(AudioFormat::FLAC) => Some(read_flac(path)),
		Some(AudioFormat::MP3) => Some(read_id3(path)),
		Some(AudioFormat::MP4) => Some(read_mp4(path)),
		Some(AudioFormat::MPC) => Some(read_ape(path)),
		Some(AudioFormat::OGG) => {
			// Most people will be using .ogg for Vorbis files
			match Some(read_vorbis(path)) {
				Some(Ok(d)) => Some(read_vorbis(path)),
				Some(Err(e)) => {
					// But check for Opus just in case someone is using .ogg as a pseudo extension
					match Some(read_opus(path)) {
						Some(Ok(d)) => Some(read_opus(path)),
						Some(Err(e)) => {
							error!("Error while reading file metadata for '{:?}': {}", path, e);
							None
						}
						None => None,
					}
				}
				None => None,
			}
		},
		Some(AudioFormat::OPUS) => Some(read_opus(path)),
		None => None,
	};
	match data {
		Some(Ok(d)) => Some(d),
		Some(Err(e)) => {
			error!("Error while reading file metadata for '{:?}': {}", path, e);
			None
		}
		None => None,
	}
}
```
