### ISSUE TITLE
Polaris 0.12.4 Windows Installer detected as a threat by SmartScreen

### ISSUE THREAD

**Issue by occlu** [agersant/polaris#99]
I just downloaded the Polaris_0.12.4.msi installer from https://github.com/agersant/polaris/releases/tag/0.12.4 and Windows Defender SmartScreen warned me of a potential threat:

![SmartScreen](https://i.imgur.com/cK32zef.jpg)

It is in french but this is the common SmartScreen message: Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

I'm just dropping that here, I had no other plan than to test this app out of curiosity.

OS: Windows 10

**Comment by agersant** [comment]
Thank you for the report!

Unfortunately, the only way to make a "trustworthy" application is to pay hundreds of dollars a year, for the sole benefit of removing this alarming popup. (StackOverflow writeup: https://stackoverflow.com/questions/252226/signing-a-windows-exe-file)

This is not something I would like spend money on (mine or anyone else's). If some users don't trust the installer published on Github despite the source and build process being publicly available, they would be welcome to make their own builds.

As a Windows user myself, I would recommend disabling Smartscreen entirely as it is only useful to the most gullible users (which you probably aren't if you're checking out self-hosted software on Github).
